/*
	Premodel File for GNBox Generated by NetworkDesigner
	Number of species: 2
*/


:-module(premodel_oscillo,[premodel/1]).

premodel(Premodel) :-
	Premodel = [Species, LI, Nb_thr, Thr_ord],
	Species = [x_0,x_1],
	LI = 
	[
	c(x_0,[i(x_0,1), i(x_1,1)]),
	c(x_1,[i(x_0,1)])
	],

	Nb_thr = [1,1],
	Thr_ord = [].
